# Site settings
title: "DFA Rice"
email: rice@designforamerica.com
description: "Design For America, Rice Chapter"
url: "http://dfarice.com"
github_username: dfarice
paginate: 5
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown
permalink: pretty
analytics:
  provider: google
  google:
      tracking_id: 'UA-52838738-1'