# Site settings
title: "DFA Rice | Blog"
email: rice@designforamerica.com
description: "Testing Jekyll as a blog engine"
baseurl: ""
url: "blog.dfarice.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
