# Site settings
title: "DFA Rice | Blog"
email: rice@designforamerica.com
description: "Design For America, Rice Chapter"
baseurl: ""
url: "http://blog.dfarice.com"
github_username: dfarice
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
permalink: pretty
